2022-11-07 10:41:10,121 INFO    MainThread:23344 [wandb_setup.py:_flush():68] Configure stats pid to 23344
2022-11-07 10:41:10,121 INFO    MainThread:23344 [wandb_setup.py:_flush():68] Loading settings from C:\Users\ASUS\.config\wandb\settings
2022-11-07 10:41:10,121 INFO    MainThread:23344 [wandb_setup.py:_flush():68] Loading settings from G:\yolov7\wandb\settings
2022-11-07 10:41:10,121 INFO    MainThread:23344 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-07 10:41:10,121 INFO    MainThread:23344 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-07 10:41:10,121 INFO    MainThread:23344 [wandb_init.py:_log_setup():476] Logging user logs to G:\yolov7\wandb\run-20221107_104110-ebvdr26j\logs\debug.log
2022-11-07 10:41:10,122 INFO    MainThread:23344 [wandb_init.py:_log_setup():477] Logging internal logs to G:\yolov7\wandb\run-20221107_104110-ebvdr26j\logs\debug-internal.log
2022-11-07 10:41:10,122 INFO    MainThread:23344 [wandb_init.py:init():516] calling init triggers
2022-11-07 10:41:10,122 INFO    MainThread:23344 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-07 10:41:10,122 INFO    MainThread:23344 [wandb_init.py:init():569] starting backend
2022-11-07 10:41:10,122 INFO    MainThread:23344 [wandb_init.py:init():573] setting up manager
2022-11-07 10:41:10,124 INFO    MainThread:23344 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-11-07 10:41:10,129 INFO    MainThread:23344 [wandb_init.py:init():580] backend started and connected
2022-11-07 10:41:10,129 INFO    MainThread:23344 [wandb_init.py:init():658] updated telemetry
2022-11-07 10:41:10,130 INFO    MainThread:23344 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-07 10:41:15,298 WARNING MsgRouterThr:23344 [router.py:message_loop():77] message_loop has been closed
2022-11-07 10:41:20,257 ERROR   MainThread:23344 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "F:\Programes\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "F:\Programes\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 697, in init
    result = handle.wait(
  File "F:\Programes\Python\Python38\lib\site-packages\wandb\sdk\lib\mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
